apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ange-teste 
spec:
  selector:
    matchLabels:
      app: app-ange-teste
  template:
    metadata:
      labels:
        app: app-ange-teste
    spec:
      containers:
        - image: okteto.dev/java-gradle-app-ange-teste:1.0.0
          name: app-ange-teste

---

apiVersion: v1
kind: Service
metadata:
  name: app-ange-teste
spec:
  type: ClusterIP
  ports:
    - name: "app-ange-teste"
      port: 8080
  selector:
    app: app-ange-teste

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ange-teste
  annotations:
    dev.okteto.com/generate-host: app-ange-teste
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-ange-teste
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific